name: action-base

on:
  push:
  workflow_dispatch:

jobs:
  gitHubInfos:
    name: Get GitHub Info
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Info
        id: github_info
        shell: bash
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_ENV

        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}