name: action-base

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - information
          - warning
          - debug
          - Develop
          - Preproduction
          - production
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  gitHubInfos:
    name: Get GitHub Info
    runs-on: ubuntu-latest

    steps:
      - name: Set GitHub details
        id: gidetails
        shell: bash
        run: |
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get env selection
        id: envSelection
        shell: bash
        run: |
          echo "Selected environment: ${ENV_INPUT}"
        env:
          ENV_INPUT: ${{ github.event.inputs.environment }}
      
      - name: CHECKOUT
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install modules
        id: installModules
        shell: bash
        run: |
          if [ -f package.json ]; then
            npm ci --prefer-offline --no-audit --progress=false
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Build project (with debug)
        id: buildProject
        shell: bash
        run: |
          set -euxo pipefail
          echo "Working dir: $(pwd)"
          ls -la
          if [ -f Makefile ]; then
            echo "---- Makefile ----"
            sed -n '1,200p' Makefile || true
            echo "---- Run make build ----"
            make build || { echo "Make failed with exit code $?"; exit 1; }
          elif [ -f  ] && npm run | grep -q "build"; then
            npm run build
          else
            echo "No build step found. Skipping build."
          fi

      - name: upload artfact
        uses: actions/upload-artifact@v4
        with:
          name: project-build
          path: dist/
    
  Download: 
      name: Download build artifact
      runs-on: ubuntu-latest  
      
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: project-build
