name: action-base

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - information
          - warning
          - debug
          - Develop
          - Preproduction
          - production
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  gitHubInfos:
    name: Get GitHub Info
    runs-on: ubuntu-latest

    steps:
      - name: Set GitHub details
        id: gidetails
        shell: bash
        run: |
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get env selection
        id: envSelection
        shell: bash
        run: |
          echo "Selected environment: ${ENV_INPUT}"
        env:
          ENV_INPUT: ${{ github.event.inputs.environment }}
      
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup Node.js and cache npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install modules
        id: installModules
        shell: bash
        run: |
          if [ -f package.json ]; then
            npm ci --prefer-offline --no-audit --progress=false
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Build project (conditional)
        id: buildProject
        shell: bash
        run: |
          if [ -f package.json ] && npm run | grep -q "build"; then
            npm run build
          elif [ -f Makefile ]; then
            make build
          else
            echo "No build step found (no package.json build script or Makefile). Skipping build."
          fi