name: new-action

on:
  push:
    branches:
      - main

jobs:
  show-github-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set GitHub Info
        id: github_info
        shell: bash
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME"

      - name: Print GitHub context
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_CONTEXT=$GITHUB_CONTEXT"